### ISSUE TITLE
Headless CMS

### ISSUE THREAD

**Issue by bromso** [cyprusjs/CyprusJS#11]
**In my first talk, I will talk of the benefits of:**
- Headless CMS (also called Content Management Framework - CMF)
- Compare [Wordpress RestAPI](https://developer.wordpress.org/rest-api/) (CMS) Vs. [Strapi.io](https://strapi.io/) (CMF)
- Alternatives to Strapi

**I will demonstrate:**
- Live coding and creation of a app/blog using GatsbyJS + Strapi with offline support

**Comment by PatrickHeneise** [comment]
Sounds great!

**Comment by the-architect** [comment]
@bromso thank you for the presentation. Can you upload it somewhere? :)

**Comment by bromso** [comment]
Thank you! :)

Next time, I will be sure to have everything installed so I could have shown the actual integration... But, you live, you learn.

Sure!

### My presentation
https://drive.google.com/open?id=1NmP_XX2PLqnlDYXnyK4DsbpQeItndtJ8tOYeOxmBmJ8

---

### Sources I've used for creating my slide presentation:
* [Jamstack.org](http://JamStack.org) 
* [HeadlessCMS.org](http://HeadlessCMS.org )
* [Storyblok Article of Headless CMS - Article "might have a _LITTLE_ biased approached because Storblok is a Headless CMS ;) ](https://www.storyblok.com/tp/headless-cms-explained)

---

### Resources:
* [NodeJS](http://Nodejs.org) 
* [Strapi.io](http://Strapi.io )
* [GatsbyJS](http://GatsbyJS.org)
* [YouTube Tutorial of Strapi & Gatsby](https://www.youtube.com/watch?list=PL7Q0DQYATmvgGiz0MbbsMA_aB1V0yLE7a&v=It4PRFJJaF0)

---

### Stack Used in the Tutorial
* [NodeJS](http://Nodejs.org) 
* [NPM](http://Nodejs.org) 
* [Strapi.io](http://Strapi.io)
* [GatsbyJS](http://GatsbyJS.org)
* [GatsbyJS Themes](https://www.gatsbyjs.org/starters/)
* [GatsbyJS Plugins](https://www.gatsbyjs.org/plugins/)
* [SailsJS](https://sailsjs.com/)
* [MongoDB](https://www.mongodb.com/)

---

### Strapi also supports these databases, out-of-the-box
* [PostgreSQL](https://www.postgresql.org/)
* [MySQL](https://www.mysql.com/)
* [MariaDB](https://mariadb.org/)
* [SQLite](https://www.sqlite.org/)

---

### Open-source alternatives to Strapi
#### Open-Source
* [Netlify CMS](https://www.netlifycms.org/)
* [Ghost](https://ghost.org/)

#### Closed-source
* [Contentful](https://www.contentful.com/)
* [Flamelink (based on the Firebase eco-system)](https://flamelink.io/)

#### (Mutated) Headless CMS as a service with Wordpress as the underlying CMS
* [Shifter](https://getshifter.io/)

For even more information, please go to [HeadlessCMS.org](http://HeadlessCMS.org ). You can search and filter your way forward in order for you to find a Headless CMS based out of your needs.

---

### Tech that would have improved the app that I was trying to show on stage
* [StorybookJS - Manage all of your UI components better](https://storybook.js.org/)
* [LernaJS - Manage multiple NPM packages](https://github.com/lerna/lerna)
