### ISSUE TITLE
Web Сomponents as Possible Future.

### ISSUE THREAD

**Issue by sgrishchenko** [cyprusjs/CyprusJS#16]
How to develop SPA in component style without using additional libraries **today**.

**Comment by alexomee** [comment]
@sgrishchenko will you be able to make this talk on August 22nd?

**Comment by sgrishchenko** [comment]
@alexandr-bbm Yes, of course

**Comment by ML6503** [comment]
Hi, do you have any presentation video  / code to see for those who missed the event?
Thanks in advance

**Comment by sgrishchenko** [comment]
Yes, I have this [repo ](https://github.com/sgrishchenko/web-components-todos) with code, but unfortunately I forgot video

**Comment by sgrishchenko** [comment]
And I have deployed app with final result
https://sgrishchenko.github.io/web-components-todos/

**Comment by ML6503** [comment]
thanks a lot
