### ISSUE TITLE
Yarn 2 package manager

### ISSUE THREAD

**Issue by larixer** [cyprusjs/CyprusJS#20]
On an upcoming event in Limassol I would like to tell about soon to be released Yarn 2 package manager, its best upcoming features and new approaches:
- Plugins
- Built-in shell for cross-platform scripts
- Zero-installs
- Zip loading
- New plug'n'play module resolution scheme
- Nested workspaces
- New workspace foreach command
- Node_modules compatibility layer

**Comment by PatrickHeneise** [comment]
@vlasenko could you give the talk next week?

**Comment by larixer** [comment]
@PatrickHeneise Yep

**Comment by PatrickHeneise** [comment]
Great, let's schedule this then! Thank you!
