### ISSUE TITLE
From Jazz Guitarist to JavaScript Developer

### ISSUE THREAD

**Issue by mostmojo** [cyprusjs/CyprusJS#21]
After 12+ years as a musician, I became a developer. The what, the how and the why. I will also draw upon the similarities and differences of playing an instrument and coding in general. 

A brief of what the talk will be like [here](https://medium.com/le-wagon/why-i-transitioned-from-jazz-guitarist-to-web-developer-57069b27232 )

**Rough Summary**

Disciplines of music vs coding
Time
Effort
Persistence
'Bugs'
Continuous stepping stones / drilling scales

Post performance vs post product launch reflection
Learning a language - reading the stave vs reading a text editor (notes, rests vs curly brackets, for loops, etc)
Brief comparison of some JavaScript code vs a sheet of music - can you see the similarities?
Deploying vs Mastering
Learning the fundamentals and jumping to other frameworks vs learning the theory and applying to another instrument
'The ongoing quest as a life long learner'
How developing and music is both technical, thus the jump is not as scary as it seems. (Use examples)

**Comment by PatrickHeneise** [comment]
Sounds great. Would be great to have a short abstract/summary of the talk in the description, since medium articles may contain a paywall.

Where and when could you give that talk?

**Comment by mostmojo** [comment]
Sure! This would be for the 21st Nov. talk in Nicosia :)

**Comment by PatrickHeneise** [comment]
Scheduled! Thank you!
