### ISSUE TITLE
wasm.Rustify::all(things).await

### ISSUE THREAD

**Issue by elpiel** [cyprusjs/CyprusJS#24]
### Introduction talk to Wasm :spider_web: and Rust :crab: :
1. What is Wasm anyway?
2. What is Rust?
3. Why should you choose Wasm, especially why with Rust.
4. How can you start hacking today!

**Comment by PatrickHeneise** [comment]
Thanks for the proposal! When and where would you like to give this talk?

**Comment by elpiel** [comment]
I would like to give it on 21 November in Nicosia. I saw there is a free spot and will give me a kick to do it this week and practice enough :)

**Comment by PatrickHeneise** [comment]
Excellent, let's do that! Scheduling you for Nov 21. Thanks!
