### ISSUE TITLE
How You May Have Come Up With React

### ISSUE THREAD

**Issue by zanlib0** [cyprusjs/CyprusJS#26]
The talk concerns the fundamental idea of React Components and how one might have stumbled upon that idea themselves, walking through an example vanilla JS application that fetches data from a backend service.

**Comment by PatrickHeneise** [comment]
That's great to hear, thanks! 

We had a talk about Web Components in August in Limassol, please check out https://github.com/cyprusjs/CyprusJS/issues/16 to avoid duplication.

Can you edit the description to give an outline of your talk only? We pull the description as abstract on our website.

**Comment by zanlib0** [comment]
>We had a talk about Web Components in August in Limassol, please check out #16 to avoid duplication.

I'm pretty sure it's going to be different than that but I'd be glad to send you the slides if you'd like to review it.

**Comment by zanlib0** [comment]
Unfortunately due to the schedule change I can't present this one. Sorry about that :(

**Comment by PatrickHeneise** [comment]
Thanks for the proposal and sorry for the change!
