### ISSUE TITLE
Under the hood of Git

### ISSUE THREAD

**Issue by steffen** [cyprusjs/CyprusJS#33]
Many work with Git daily. In this "no slides" talk we will look under the hood of Git in the console.

We will look at how Git stores objects, what objects types exist and what references are.
We'll leverage tools such as [`git-sizer`](https://github.com/github/git-sizer) and [`git-filter-repo`](https://github.com/newren/git-filter-repo) to understand the health of a repository.
We may also touch on Git's performance tracing capabilities (e.g. [GIT_TRACE2](https://git-scm.com/docs/api-trace2)), [Git LFS](https://git-lfs.github.com/) and monorepos depending on time and interest.

**Comment by PatrickHeneise** [comment]
Scheduled for Friday, July 9, 6pm 

RSVP here: https://www.meetup.com/cyprusjs-paphos/events/279017343

**Comment by larixer** [comment]
@steffen Could you also touch on the topic of storing non-text files and archives into Git and built-in Git capabilities for handling differences between archives, like what archives are better to store into Git, compressed vs uncompressed, with LFS or without LFS.

**Comment by steffen** [comment]
> @steffen Could you also touch on the topic of storing non-text files and archives into Git and built-in Git capabilities for handling differences between archives, like what archives are better to store into Git, compressed vs uncompressed, with LFS or without LFS.

@larixer 💯 I definitely will! 🙂 Thanks for the suggestion! Let me know if there is anything else you would like me to touch on!
