### ISSUE TITLE
Powerful frontend app architecture with mobx + react

### ISSUE THREAD

**Issue by anri-asaturov** [cyprusjs/CyprusJS#4]
Hey, this is me https://stackoverflow.com/story/anri
I can talk pretty much about anything javascript.
Recently I've come up with a new vision of frontend architecture that I'm happy about and can share.

**Comment by PatrickHeneise** [comment]
My experience with mobx wasn't great, so I'd love to learn more about this.

When and where would be good for you?

**Comment by anri-asaturov** [comment]
I live in Limassol so, that would be best, date doesn't matter as long as I have a week to prepare

**Comment by orlov-vo** [comment]
@anri-asaturov, you collect enough votes and we will glad to see you at Limassol meetup on 23 May with this talk

**Comment by orlov-vo** [comment]
@anri-asaturov, you collect enough votes and we will glad to see you at Limassol meetup on 23 May with this talk

**Comment by PatrickHeneise** [comment]
@anri-asaturov can you please confirm availability?

**Comment by anri-asaturov** [comment]
Hey, sorry, unfortunately I have to be out of Cyprus in the end of May

**Comment by PatrickHeneise** [comment]
Oh that's too bad! Next time then!

**Comment by PatrickHeneise** [comment]
@anri-asaturov how about next week in Nicosia?

**Comment by PatrickHeneise** [comment]
@anri-asaturov how's August 22nd?

**Comment by anri-asaturov** [comment]
@PatrickHeneise hello, in Limassol I can.

**Comment by PatrickHeneise** [comment]
Excellent. You’re up :)

**Comment by anri-asaturov** [comment]
@PatrickHeneise do I need to send you a presentation beforehand or smth? How many ppl are expected?

**Comment by alexomee** [comment]
@anri-asaturov 

@orlov-vo and I are organising CyprusJS events in Limassol. In the last event there were around 20 people but we will do a better marketing this time.

it would be nice if you can send a presentation beforehand and, in case you are interested, we can have a a rehearsal to make your talk even better.

feel free to contact me directly (https://t.me/alexandr_bbm) for the all further questions

**Comment by PatrickHeneise** [comment]
No need to send the presentation before, but if you’d like to rehearse or get some feedback, @alexandr-bbm can help.

Technical information about the setup and format can be found in the readme of this repo.
