### ISSUE TITLE
Talk Proposal: GraphQL Schemas with Nexus

### ISSUE THREAD

**Issue by PatrickHeneise** [cyprusjs/CyprusJS#42]
### Abstract

Everyone has probably heard of and likely used a GraphQL API by now. Some may have created their own GraphQL servers with Postgraphile. In this talk I'll demonstrate how to write your own schemas for special occasions, such as time series IoT databases or to combine multiple data sources into a single query.

### Your name (and pronouns)

Patrick Heneise (he/him)

### Contact Details

https://twitter.com/PatrickHeneise

### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://berlincodeofconduct.org/)

**Comment by saitonakamura** [comment]
https://github.com/PatrickHeneise/talk-graphql-nexus
