### ISSUE TITLE
Car pooling for CyprusJS Nicosia, June 27

### ISSUE THREAD

**Issue by PatrickHeneise** [cyprusjs/CyprusJS#5]
I'm driving from Larnaca and have 3 seats available. I'll leave a bit earlier to visit the northern part of the city for a coffee :)

**Comment by leisa218** [comment]
I'm driving from Polis and have 2 seats available.

**Comment by PatrickHeneise** [comment]
Wow, that's far!

**Comment by leisa218** [comment]
> Wow, that's far!

Willing to get people in from Limassol or Larnaca

**Comment by PatrickHeneise** [comment]
Maybe @bromso ?

**Comment by bromso** [comment]
I’m driving from Paphos. Have 3 seats available.

**Comment by PatrickHeneise** [comment]
Maybe you can pool with @leisa218 ?

**Comment by bromso** [comment]
Sure, I can pickup people from Limassol. People need to know that I have two German Shepherds (I will not bring them to the event, I try to keep my car as clean as I can but people need to know that there are certainly dog hairs in my car if you are allergic). 
@leisa218 please contact DM me with all the specifics, preferable on twitter:
https://twitter.com/jonasbroms

**Comment by leisa218** [comment]
@bromso I'm located in Polis. Pick up at Limassol would be difficult for me. What about the other way around?

**Comment by leisa218** [comment]
> I'm driving from Polis and have 2 seats available.

UPDATE: 

I go from Polis to Paphos around 13:00, and then from Paphos to Nicosia around 15:00 - 15:30.

**Comment by bromso** [comment]
I would love to go with you then! I will send details as a DM on Twitter.
