### ISSUE TITLE
Discussion: I18n / I10n of javascript applications

### ISSUE THREAD

**Issue by the-architect** [cyprusjs/CyprusJS#8]
I would be very interested in a talk about full stack I18n / I10n of javascript applications.

- Which framework should I use based on ease of use, flexibility and feature set?
- How to handle i18n in the database? (ie: MongoDB)
- Ease of integration with localization services like PhraseApp, Locize etc
- Best practices and pitfalls

**Comment by PatrickHeneise** [comment]
This varies a lot between frameworks. Can you narrow it down?

**Comment by the-architect** [comment]
I edited the request. :)

**Comment by PatrickHeneise** [comment]
@the-architect if you need "translation as a service", check out these tools:

- https://react.i18next.com
- https://localizejs.com
