### ISSUE TITLE
Scalable Modular UI/UX Elements Using Angular 2/7

### ISSUE THREAD

**Issue by ProZillaZ** [cyprusjs/CyprusJS#9]
In 30 minutes I can be talking about the logic and the setup of a scalable and modular UI engine using Angular 2/6 for people who are looking to develop scalable applications for big projects. 

I will be exploring different options using Angular components and SCSS capabilities to perform the logic and the structure.

You're welcome to suggest anything else you want to know.

**Comment by ProZillaZ** [comment]
I live in Larnaca but I can do the talk in any city :)

**Comment by PatrickHeneise** [comment]
Excellent, thank you! We don't have a venue in Larnaca yet, but we can car-pool to Limassol next month if that's OK for you?

**Comment by ProZillaZ** [comment]
No problem. Please communicate with me through my email hessan@sorxmedia.com and let me know any updates. Also please let me know how are the talks are structured and should be delivered :)

**Comment by orlov-vo** [comment]
@ProZillaZ, you collect enough votes and we will glad to see you at Limassol meetup on 23 May with this talk

**Comment by ProZillaZ** [comment]
Thanks! Can you please be more specific where is the venue and how you want to the talk to be? The structure?

**Comment by PatrickHeneise** [comment]
@ProZillaZ the event will be at "ARIS" https://ti.to/cyprusjs/cyprusjs-limassol. It's in the center of Limassol. The talk should be no longer than 30 minutes and we've added some more technical details here: https://github.com/cyprusjs/talks/blob/master/README.md#limassol-λεμεσός-limassol-chapter

**Comment by the-architect** [comment]
@ProZillaZ thank you for the presentation. Can you upload it somewhere? :)

**Comment by ProZillaZ** [comment]
Sure: https://sorxmedia.com/files/scalable-modular-ui.ppsx
